#!/bin/bash

# Back-up van Persoonlijke map maken.

source=$HOME
target=$(ls --directory /media/"$USER"/* 2> /dev/null)
if [[ -z $target || $(echo "$target" | wc --lines) -gt 1 ]]; then
    echo 'Sluit één USB-harddisk aan.'
    exit 1
fi

rsync   --archive                   \
        --verbose                   \
        --human-readable            \
        --delete                    \
        "$source"/                  \
        "$target/backup-$HOSTNAME-$USER"
