#!/bin/bash
target=$(ls --directory /media/"$USER"/*)
distro=$(lsb_release --id --short | tr '[:upper:]' '[:lower:]')

rsync   --archive                                   \
        --verbose                                   \
        --human-readable                            \
        --delete                                    \
        --exclude='.adobe/Flash_Player/AssetCache'  \
        --exclude='.cache'                          \
        --exclude='.ccache'                         \
        --exclude='.git'                            \
        --exclude='.gvfs'                           \
        --exclude='.Private'                        \
        --exclude='__pycache__'                     \
        --exclude='.recent-applications.xbel'       \
        --exclude='.recently-used.xbel'             \
        --exclude='snap/*/*/.cache'                 \
        --exclude='.steam/root'                     \
        --exclude='.thumbnails'                     \
        --exclude='.var/app/*/cache'                \
        --exclude='.xsession-errors'                \
        --delete-excluded                           \
        --ignore-errors                             \
        "$HOME"/                                    \
        "$target"/backup-"$HOSTNAME"-"$distro"-"$USER"

# rsync error: some files/attrs were not transferred (see previous errors):
# chmod a+r /home/$USER/.config/nautilus-actions
# chmod 775 /home/$USER/.local/share/teamviewer*/drive_c/users/karel/*
