#!/bin/bash
# shellcheck source=kz-common.sh
###############################################################################
# Webbestanden valideren.
#
# Geschreven door Karel Zimmer <printf '%s\n'@karelzimmer.nl>.
###############################################################################
set -o errexit
set -o nounset

###############################################################################
# Constants
###############################################################################

program_name='ckhtml'

css_dir=$HOME/kz-uploads/dist/css
html_dir=$HOME/kz-uploads/dist/html

home_url=https://karelzimmer.nl
css_url=$home_url/css
html_url=$home_url/html

css_validator_url='http://jigsaw.w3.org/css-validator/validator?uri='
html_validator_url='http://validator.w3.org/check?uri='

###############################################################################
# Variables
###############################################################################

###############################################################################
# Functions
###############################################################################

function process_input {
    local       dir=''
    local -i    number_of_processes=0

    for dir in "$css_dir" "$html_dir"; do
        if ! [[ -d $dir ]]; then
            printf '%s\n' "$program_name: map '$dir' bestaat niet"
            exit 1
        fi
    done

    number_of_processes=$(
        pgrep --count --full '/opt/google/chrome/chrome' || true
        )
    if [[ $number_of_processes -eq 0 ]]; then
        printf  '%s\n%s\n'                                      \
                'Google Chrome webrowser is nog niet gestart,'  \
                'start nu eerst de Google Chrome webrowser.'
        read -rp "Druk op Enter-toets wanneer Google Chrome webrowser is \
gestart [Enter]: "
        number_of_processes=$(
            pgrep --count --full '/opt/google/chrome/chrome' || true
            )
        if [[ $number_of_processes -eq 0 ]]; then
            printf '%s\n' 'Google Chrome webrowser is niet gestart.'
            exit 1
        fi
    fi

    validate_css
    validate_html
}


function validate_css {
    local filename=''

    cd "$css_dir" || exit 1

    for filename in *.css; do
        google-chrome "$css_validator_url$css_url/$filename"
    done
}


function validate_html {
    local filename=''

    cd "$html_dir" || exit 1

    for filename in *.html; do
        google-chrome "$html_validator_url$html_url/$filename"
    done
}


function term_script {
    printf '%s\n' 'Controleer de tabbladen in Google Chrome.'
    exit 0
}

###############################################################################
# Script
###############################################################################

function main {
    process_input
    term_script
}

main "$@"
