#!/usr/bin/env bash
# shellcheck source=common.sh
###############################################################################
# SPDX-FileComment: Webbestanden valideren
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################

###############################################################################
# Imports
###############################################################################

source common.sh


###############################################################################
# Constants
###############################################################################

readonly PROGRAM_NAME='ckhtml'

readonly CSS_DIR=$HOME/kz-uploads/dist/css
readonly HTML_DIR_NL=$HOME/kz-uploads/dist/html/nl
readonly HTML_DIR_EN=$HOME/kz-uploads/dist/html/en

readonly HOME_URL=https://karelzimmer.nl
readonly CSS_URL=$HOME_URL/css
readonly HTML_URL_NL=$HOME_URL/html/nl
readonly HTML_URL_EN=$HOME_URL/html/en

readonly CSS_VALIDATOR_URL='http://jigsaw.w3.org/css-validator/validator?uri='
readonly HTML_VALIDATOR_URL='http://validator.w3.org/check?uri='


###############################################################################
# Functions
###############################################################################

function process_input {
    local       DIR=''
    local -i    NUMBER_OF_PROCESSES=0

    for DIR in "$CSS_DIR" "$HTML_DIR_NL" "$HTML_DIR_EN"; do
        if ! [[ -d $DIR ]]; then
            printf '%s\n' "$PROGRAM_NAME: map '$DIR' bestaat niet"
            exit 1
        fi
    done

    NUMBER_OF_PROCESSES=$(
        pgrep --count --full '/opt/google/chrome/chrome' || true
        )
    if [[ $NUMBER_OF_PROCESSES -eq 0 ]]; then
        printf  '%s\n%s\n'                                      \
                'Google Chrome webrowser is nog niet gestart,'  \
                'start nu eerst de Google Chrome webrowser.'
        read -rp "Druk op Enter-toets wanneer Google Chrome webrowser is \
gestart [Enter]: "
        NUMBER_OF_PROCESSES=$(
            pgrep --count --full '/opt/google/chrome/chrome' || true
            )
        if [[ $NUMBER_OF_PROCESSES -eq 0 ]]; then
            printf '%s\n' 'Google Chrome webrowser is niet gestart.'
            exit 1
        fi
    fi

    validate_css
    validate_html
}


function validate_css {
    local FILENAME=''

    cd "$CSS_DIR" || exit 1

    for FILENAME in *.css; do
        google-chrome "$CSS_VALIDATOR_URL$CSS_URL/$FILENAME"
    done
}


function validate_html {
    local FILENAME=''

    cd "$HTML_DIR_NL" || exit 1

    for FILENAME in *.html; do
        google-chrome "$HTML_VALIDATOR_URL$HTML_URL_NL/$FILENAME"
    done

    cd "$HTML_DIR_EN" || exit 1

    for FILENAME in *.html; do
        google-chrome "$HTML_VALIDATOR_URL$HTML_URL_EN/$FILENAME"
    done
}


function term_script {
    printf '%s\n' 'Controleer de tabbladen in Google Chrome.'
    exit 0
}

###############################################################################
# Main
###############################################################################

function main {
    init_script
    process_input
    term_script
}

main "$@"
