#!/bin/bash
set -o errexit
set -o nounset

# ckyear: check for (copyright) year

last_year=${1:-$(date '+%Y' --date='last year')}
date '+%Y' -d "$last_year" 1> /dev/null
output=/tmp/cknwyr.log

cd "$HOME"

echo "ckyear: check for (copyright) year" > $output
{
    echo
    echo "Dir.: $HOME"
    echo "Year: $last_year"
    echo 
} >> $output

while read -r file; do
    case $file in
        *.deb|*.gif|*.ico|*.pdf|*.png|*.svg)
            continue
            ;;
        *)
            echo "$file" >> $output
            grep "$last_year" "$file" &>> $output|| true
            echo >> $output
            ;;
    esac
done < <(
        find ./kz-*                 \
        -type f                     \
        -not -path './kz-deb/*'     \
        -not -path './*/.git*'      \
        -not -path './*/dist*'      \
        -not -path '*/__pycache__*' \
        -not -name kz.mo            \
        -not -name kz.po            \
        -not -name kz.pot           \
        -not -name license          \
        -not -name LICENSE          \
        -not -name README           \
        -not -name README.md        \
        -print                      |
        sort
        )

less $output
