#!/usr/bin/env bash
# shellcheck shell=bash
# #############################################################################
# SPDX-FileComment: Distribute personal Bash scripts
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

# List NORMAL last here so that -x doesn't bork the display.
bold='\033[1m'
green=$bold'\033[32m'
normal=$bold'\033[0m'

# Where the the code is stored locally.
origin=$(xdg-user-dir PROJECTS)

# #############################################################################
# Main
# #############################################################################

# Fill ~/bin with repo bin.
rsync   --archive               \
        --verbose               \
        --exclude='LICENSE'     \
        --exclude='README.md'   \
        --exclude='.git*'       \
        "$origin/bin"           \
        "$HOME"

printf '%b\n' "${green}Klaar!${normal}"
exit 0
