#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Show all local git branches in the home directory
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

# List NORMAL last here so that -x doesn't bork the display.
readonly BOLD='\033[1m'
readonly GREEN='\033[1;32m'
readonly NORMAL='\033[0m'

declare repo=''


# #############################################################################
# Main
# #############################################################################

while read -r repo; do
    printf "${BOLD}Branch %s...${NORMAL}\n" "$repo"
    cd "$HOME/$repo" || exit 1
    git branch --all --verbose
    printf '\n'
done < <(
        find    "$HOME"         \
                -type   d       \
                -name   '.git'  \
                -printf '%P\n'  |
        sed     's|/.git||'     |
        sort
        )

printf '%b\n' "${GREEN}Klaar!${NORMAL}"
exit 0
