#!/usr/bin/bash

# gitbranch: show all local git branches

repo_list=$(
    find    "$HOME"         \
		   	-maxdepth 2     \
            -name .git      \
            -type d         \
            -print          |
    cut     --delimiter='/' \
            --fields=4      |
    sort
    )
newline=''
for repo in $repo_list; do
    printf "${newline}$(tput bold)%s$(tput sgr0)\n" "$repo"
    newline='\n'
    cd "$HOME/$repo" || exit 1
    git branch
done
