#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Git clone of all public remote repos in the home directory
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################
        
# List NORMAL last here so that -x doesn't bork the display.
readonly BOLD='\033[1m'
readonly GREEN='\033[1;32m'
readonly NORMAL='\033[0m'

readonly USER_NAME='karelzimmer'

declare gitroot=''
declare repo=''
declare repos=''


# #############################################################################
# Main
# #############################################################################

# Get all public repositories for <user_name> with curl via GitHub REST API,
# and extract required info with jq when available.
if type jq &> /dev/null; then
    repos=$(
        curl --silent "https://api.github.com/users/$USER_NAME/repos"   |
        jq '.[] | {name: .name}'                                        |
        jq --raw-output .name
        )
else
    repos=$(
        curl --silent "https://api.github.com/users/$USER_NAME/repos"   |
        grep --regexp='"full_name"'                                     |
        cut --delimiter=':' --fields=2-                                 |
        sed --expression='s/,//'                                        |
        sed --expression='s/"//g'                                       |
        sed --expression="s|$USER_NAME/||"
        )
fi

for repo in $repos; do
    # Skip special repository.
    if [[ $repo = "$USER_NAME" ]]; then
        continue
    fi
    # Repo bin in HOME, others in PROJECTS directory.
    if [[ $repo = 'bin' ]]; then
        gitroot="$HOME"
    else
        gitroot=$(xdg-user-dir PROJECTS)
    fi
    printf "${BOLD}Clone %s...${NORMAL}\n" "$gitroot"
    git clone "https://github.com/$USER_NAME/$repo.git" "$gitroot" || true
    printf '\n'
done

printf '%b\n' "${GREEN}Klaar!${NORMAL}"
exit 0
