#!/bin/bash
set -o errexit
set -o nounset

# Verwijder alle repo's in repo.list.

read -rp 'Alle repos verwijderen? Antwoord JA om te bevstigen: '
if [[ $REPLY != 'JA' ]]; then
    exit 1
fi

while read -r repo; do
    rm --force --recursive "${HOME/$repo:?}" || exit 1
done < "$HOME"/bin/repo.list
