#!/bin/bash
set -o errexit
set -o nounset

# gitfetch: git fetch of all <user> public repos

user=karelzimmer
# Get all public repositories for <user> with curl via GitHub REST API, and
# extract required info with jq.
repo_list=$(
    curl --silent "https://api.github.com/users/$user/repos" | jq '.[] |
    {name: .name}' | jq --raw-output .name
    )
for repo in $repo_list; do
    # Skip special repository.
    if [[ $repo = "$user" ]]; then
        continue
    fi
    printf "$(tput bold)%s$(tput sgr0)\n" "$repo"
    if [[ -d "$HOME/$repo" ]]; then
        cd "$HOME/$repo"
        git fetch
        printf '\n'
    fi
done
