#!/usr/bin/bash
###############################################################################
# SPDX-FileComment: Git fetch of all local branches
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
source "$(dirname "$0")"/bin_common.sh

readonly PROGRAM_NAME='gitfetch'

declare repo=''
declare repo_list=''

repo_list=$(
    find    "$HOME"         \
            -maxdepth 2     \
            -name .git      \
            -type d         \
            -print          |
    cut     --delimiter='/' \
            --fields=4      |
    sort
    )

for repo in $repo_list; do
    printf "${BOLD}Fetch %s$NORMAL\n" "$repo"
    cd "$HOME/$repo" || exit 1
    git fetch
done

printf "$GREEN%b$NORMAL\n" "$PROGRAM_NAME $(gettext --domain=kz 'finished')"
