#!/usr/bin/env bash
# shellcheck source=common.sh
###############################################################################
# SPDX-FileComment: Git init
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################

###############################################################################
# Imports
###############################################################################

source common.sh


###############################################################################
# Main
###############################################################################

init_script

read -rp 'Git user.name [e.g. Karel Zimmer]: '
git config --global user.name "$REPLY"

read -rp 'Git user.email [e.g. karel.zimmer@gmail.com]: '
git config --global user.email "$REPLY"

git config --global core.editor "code --wait"
git config --global pull.ff only
git config --global credential.helper store
git config --global alias.logg 'log --decorate --graph --oneline --all'

git config --list

printf '%s\n' "$(gettext 'Complete!')"
exit 0
