#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Git init
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

# List NORMAL last here so that -x doesn't bork the display.
GREEN='\033[1;32m'
NORMAL='\033[0m'


# #############################################################################
# Main
# #############################################################################

read -rp 'Git user.name [e.g. Karel Zimmer]: ' < /dev/tty
git config --global user.name "$REPLY"

read -rp 'Git user.email [e.g. karel.zimmer@gmail.com]: ' < /dev/tty
git config --global user.email "$REPLY"

git config --global core.editor "code --wait"
git config --global pull.ff only
git config --global credential.helper store
git config --global alias.logg 'log --decorate --graph --oneline --all'

git config --list

printf '%b\n' "${GREEN}Klaar!${NORMAL}"
exit 0
