#!/bin/bash
set -o errexit
set -o nounset

# Git pull (clone als nodig) van alle repo's in repo.list.

git config --global pull.ff only
git config --global credential.helper store
while read -r repo; do
    printf "$(tput bold)%s$(tput sgr0)\n" "$repo"
    if ! (cd "$HOME/$repo" && git pull); then
        git clone "https://github.com/karelzimmer/$repo.git" "$HOME/$repo"
    fi
done < "$HOME"/bin/repo.list
