#!/bin/bash
set -o errexit
set -o nounset

# Git pull (clone als nodig) van alle public repo's.

git config --global pull.ff only
git config --global credential.helper store
user=karelzimmer
# Get all public repositories for user with curl via GitHub REST API,
# extract required info with jq (Command-line JSON processor), and
# remove double qoutes with sed.
repo_list=$(
    curl --silent "https://api.github.com/users/$user/repos" |
    jq '.[] | {name: .name}' | jq .name | sed 's/"//g'
    )
for repo in $repo_list; do
    # Skip special repository.
    if [[ $repo = "$user" ]]; then
        continue
    fi
    printf "$(tput bold)%s$(tput sgr0)\n" "$repo"
    if ! (cd "$HOME/$repo" 2> /dev/null && git pull); then
        git clone "https://github.com/$user/$repo.git" "$HOME/$repo"
    fi
done
