#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Git pull of all local branches in the home directory
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

# List NORMAL last here so that -x doesn't bork the display.
bold='\033[1m'
green='\033[1;32m'
normal='\033[0m'

# Where the the code is stored locally.
origin=$(xdg-user-dir PROJECTS)
repo=''

# #############################################################################
# Main
# #############################################################################

while read -r repo; do
    printf "${bold}Pull %s...$normal\n" "$repo"
    cd "$repo" || exit 1
    git pull --all --verbose
    printf '\n'
done < <(
        find    "$origin"   \
                -maxdepth 2 \
                -name .git  \
                -type d     \
                -print      |
        sort                |
        sed     --expression='s|/.git||'
        )

printf '%b\n' "${green}Klaar!${normal}"
exit 0
