#!/bin/bash

# gitstat: git status of all local branches

repo_list=$(
    find    "$HOME"         \
		   	-maxdepth 2     \
            -name .git      \
            -type d         \
            -print          |
    cut     --delimiter='/' \
            --fields=4      |
    sort
    )
newline=''
for repo in $repo_list; do
    printf "${newline}$(tput bold)%s$(tput sgr0)\n" "$repo"
    newline='\n'
    cd "$HOME/$repo" || exit 1
    # Remove empty and known lines from output.
    git status                                                      |
        sed '/On branch main/d'                                     |
        sed '/On branch master/d'                                   |
        sed "/Your branch is up to date with 'origin\/main'./d"     |
        sed "/Your branch is up to date with 'origin\/master'./d"   |
        sed '/^$/d'                                                 |
        sed '/nothing to commit, working tree clean/d'              |
        sed '/nothing to commit, working directory clean/d'
done
