#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Git merge squash of a local branch.
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################


# #############################################################################
# Constants
# #############################################################################

# List NORMAL last here so that -x doesn't bork the display.
readonly BOLD='\033[1m'
readonly NORMAL='\033[0m'


# #############################################################################
# Globals
# #############################################################################

declare SEPARATOR_LINE=''


# #############################################################################
# Main
# #############################################################################

SEPARATOR_LINE=$(eval printf -- '=%.0s' '{1..79}')

clear -x

printf '%b\n' "$SEPARATOR_LINE

    Git squash merge in 9 stappen.
    Werkt het beste in twee aparte terminals door te kopiëren en plakken.

    Het volgende dient te worden uitgevoerd ${BOLD}per repo${NORMAL}.
    Op ${BOLD}eerste machine${NORMAL}: alle stappen
    Op ${BOLD}andere machine${NORMAL}: stappen gemerkt met *

$SEPARATOR_LINE

${BOLD}Voorbereiden...${NORMAL}
 *  1.  git branch                          # noteer samen te voegen branch
 *  2.  branch=                             # stel naam van squash-branch in

${BOLD}Samenvoegen...${NORMAL}
 *  3.  git switch main                     # schakel over naar de main branch
    4.  git merge --squash \$branch          # voer de squash merge uit

${BOLD}Bevestigen...${NORMAL}
    5.  git commit                          # stel commit-bericht op in editor
    6.  git push origin main                # push main branch naar remote

${BOLD}Opruimen...${NORMAL}
 *  7.  git branch --delete \$branch         # verwijder lokale branch
    8.  git push origin --delete \$branch    # verwijder remote branch

${BOLD}Onderhoud...${NORMAL}
 *  9.  git pull --prune                    # verwijder verouderde verwijzingen

$SEPARATOR_LINE"
exit 0
