#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Git merge squash of a local branch
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

# #############################################################################
# Imports
# #############################################################################

export TEXTDOMAIN=kz
export TEXTDOMAINDIR=/usr/share/locale
source /usr/bin/gettext.sh


# #############################################################################
# Constants
# #############################################################################

SEPARATOR_LINE=$(eval printf '=%.0s' '{1..80}')
readonly SEPARATOR_LINE
readonly FILLER='    '

# List NORMAL last here so that -x doesn't bork the display.
readonly GREEN='\033[1;32m'
readonly NORMAL='\033[0m'


# #############################################################################
# Globals
# #############################################################################


# #############################################################################
# Main
# #############################################################################

# Script-hardening.
set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# Trap exit signal.
trap 'exit $?' EXIT

printf '\n%s\n\n' "$SEPARATOR_LINE"
printf '%s\n' "$(gettext '*** git squash merge in 10 steps ***')"
printf '%s\n' ""
printf '%s\n' "$(gettext "Works best in two separate terminals by copying and \
pasting.")"
printf '%s\n' ""
printf '%s\n' "$(gettext 'The following will be executed:')"
printf '%s\n' ""
printf '%s\n' "$(gettext 'PREPARE:')"
printf '%s\n' "${FILLER}git branch              # note branch to be squashed"
printf '%s\n' "${FILLER}branch=                 # set squash branch name here"
printf '%s\n' ""
printf '%s\n' "$(gettext 'MERGE:')"
printf '%s\n' "${FILLER}git switch main"
printf '%s\n' "${FILLER}git merge --squash \$branch"
printf '%s\n' ""
printf '%s\n' "$(gettext 'COMMIT:')"
printf '%s\n' "${FILLER}git commit --message='' # set commit message here, or"
printf '%s\n' "${FILLER}git commit              # set commit message in editor"
printf '%s\n' "${FILLER}git push origin"
printf '%s\n' ""
printf '%s\n' "$(gettext 'CLEANUP:')"
printf '%s\n' "${FILLER}git branch --delete \$branch"
printf '%s\n' "${FILLER}git push origin --delete \$branch"
printf '%s\n' ""
printf '%s\n' "$(gettext 'MAINTENANCE:')"
printf '%s\n' "${FILLER}git remote prune origin # remove all stale branches"
printf '%s\n' "${FILLER}git fetch --prune       # remove all stale references"
printf '%s\n' ""
printf '%b\n' "${GREEN}$(gettext 'Complete!')${NORMAL}"
printf '\n%s\n\n' "$SEPARATOR_LINE"
exit 0
