#!/usr/bin/env bash
# shellcheck source=common.sh
###############################################################################
# SPDX-FileComment: Git status of all local branches
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
source "$(dirname "$0")"/common.sh

declare REPO=''
declare REPO_LIST=''

REPO_LIST=$(
    find    "$HOME"     \
            -maxdepth 2 \
            -name .git  \
            -type d     \
            -print      |
    sort                |
    sed     --expression='s|/.git||'
    )

for REPO in $REPO_LIST; do
    printf "${BOLD}Status %s$NORMAL\n" "$REPO"
    cd "$REPO" || exit 1
    git status --verbose
done

exit 0
