#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Git status of all local branches in the home directory.
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################


# #############################################################################
# Constants
# #############################################################################

# List NORMAL last here so that -x doesn't bork the display.
readonly BOLD='\033[1m'
readonly GREEN='\033[1;32m'
readonly NORMAL='\033[0m'


# #############################################################################
# Globals
# #############################################################################

declare REPO=''


# #############################################################################
# Main
# #############################################################################

printf '%s\n' 'Zoek naar alle Git-repositories in de Persoonlijke map...'

while read -r REPO; do
    printf "\n${BOLD}Status %s...${NORMAL}\n" "$REPO"
    cd "$HOME/$REPO" || exit 1
    git status --verbose
done < <(
        find    "$HOME"         \
                -type   d       \
                -name   '.git'  \
                -printf '%P\n'  |
        sed     's|/.git||'     |
        sort                    2> /dev/null
        )

printf '%b\n' "${GREEN}Klaar!${NORMAL}"
exit 0
