#!/bin/bash
set -o errexit
set -o nounset

# Git status van alle lokale repo's.
# Verwijder lege regels en bekende regels uit de output.

repo_list=$(
    find    "$HOME"         \
            -maxdepth 2     \
            -name .git      \
            -type d         \
            -print          |
    cut     --delimiter='/' \
            --fields=4      |
    sort
    )
for repo in $repo_list; do
    printf "$(tput bold)%s$(tput sgr0)\n" "$repo"
    cd "$HOME/$repo" || exit 1
    git status                                                  |
        sed '/On branch main/d'                                 |
        sed "/Your branch is up to date with 'origin\/main'./d" |
        sed '/^$/d'                                             |
        sed '/nothing to commit, working tree clean/d'
done