#!/usr/bin/bash
###############################################################################
# Scan netwerk voor ip-adressen (ip-address)
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
set -o errexit
set -o nounset

printf '%s\n' 'Uitvoeren ip...'
ip a
printf '\n%s\n'  'Uitvoeren nmap...'
nmap -sP 192.168.1.0/24
