#!/bin/bash
set -o errexit
set -o nounset

# Scan netwerk voor ip-adressen.

if ! command -v nmap 1> /dev/null; then
    sudo apt-get install --yes nmap
fi

printf '%s\n' 'Uitvoeren ip...'
ip a
printf '\n%s\n'  'Uitvoeren nmap...'
nmap -sP 192.168.1.0/24
