#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Delete kz GPG files.
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################


# #############################################################################
# Main
# #############################################################################

rm --verbose ~/kz-install-decrypted.sh
rm --verbose ~/kz-setup-decrypted.sh

printf '\n%s\n' 'Use "kzgpgdecrypt" to decrypt the kz GPG files.'
printf  '\n%s\n' \
        'Use "kzgpgencrypt" or "kzgpgsign" to encrypt (sign) the kz GPG files.'
