#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Delete kz GPG files
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

rm --force --verbose ~/kz-install-decrypted.sh
rm --force --verbose ~/kz-setup-decrypted.sh