#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Decrypt kz GPG files.
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################


# #############################################################################
# Constants
# #############################################################################

# Fallback if no xdg-user-dir command is available.
if ! GITROOT=$(xdg-user-dir PROJECTS 2> /dev/null); then
    GITROOT=$HOME/Projecten
fi
readonly GITROOT


# #############################################################################
# Globals
# #############################################################################


# #############################################################################
# Main
# #############################################################################

gpg --output  "$HOME/kz-install-decrypted.sh" \
    --decrypt "$GITROOT/kz-scripts/usr/bin/kz-install.sh.gpg"
printf '%s\n\n' "'$HOME/kz-install-decrypted.sh' is aangemaakt"

gpg --output  "$HOME/kz-setup-decrypted.sh"   \
    --decrypt "$GITROOT/kz-scripts/usr/bin/kz-setup.sh.gpg"
printf '%s\n\n' "'$HOME/kz-setup-decrypted.sh' is aangemaakt"

printf  '\n%s\n' \
        '====================================================================='
printf  '\n%s\n' \
        'Use "kzgpgencrypt" or "kzgpgsign" to encrypt (sign) the kz GPG files.'
printf '\n%s\n' 'Use "kzgpgdelete" to delete the decrypted kz GPG files.'
