#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Encrypt (sign) kz GPG files
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

GITROOT=$(xdg-user-dir PROJECTS)
readonly GITROOT


# #############################################################################
# Main
# #############################################################################

gpg --output "$GITROOT/kz-scripts/usr/bin/kz-install.sh.gpg" \
    --sign   ~/kz-install-decrypted.sh
gpg --output "$GITROOT/kz-scripts/usr/bin/kz-setup.sh.gpg"   \
    --sign   ~/kz-setup-decrypted.sh

printf '\n%s\n' 'Use "kzgpgdelete" to delete the decrypted kz GPG files.'
printf '\n%s\n' 'Use "kzgpgdecrypt" to decrypt the kz GPG files.'
