#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Decrypt kz GPG files.
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################


# #############################################################################
# Constants
# #############################################################################

if ! GITROOT=$(xdg-user-dir PROJECTS); then
    GITROOT=$HOME/Projecten
fi
readonly GITROOT


# #############################################################################
# Globals
# #############################################################################


# #############################################################################
# Main
# #############################################################################

gpg --output  ~/kz-install-decrypted.sh \
    --decrypt "$GITROOT/kz-scripts/usr/bin/kz-install.sh.gpg"
gpg --output  ~/kz-setup-decrypted.sh   \
    --decrypt "$GITROOT/kz-scripts/usr/bin/kz-setup.sh.gpg"

printf  '\n%s\n' \
        'Use "kzgpgencrypt" or "kzgpgsign" to encrypt (sign) the kz GPG files.'
printf '\n%s\n' 'Use "kzgpgdelete" to delete the decrypted kz GPG files.'
