#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Decrypt kz GPG files
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

gpg --output  ~/kz-install-decrypted.sh \
    --decrypt ~/kz-scripts/usr/bin/kz-install.sh.gpg
gpg --output  ~/kz-setup-decrypted.sh   \
    --decrypt ~/kz-scripts/usr/bin/kz-setup.sh.gpg