#!/bin/bash

# Maak lijst van alle ~/kz-scripts

# Instellingen

readonly PROGNAME=lsash
if [[ $1 ]]; then
    echo "Gebruik: $PROGNAME"
    exit 0
fi

# Globale constanten

# Globale variabelen

# Functies

# Hoofdlijn

cd "$HOME"/kz-scripts || exit 1

readonly ERASE_LINE="$(tput el)\c"
readonly UP_1_LINE=$(tput cuu1)

declare opdr1=''
declare opdr2=''

opdr1="(
    find    .                   \
            -maxdepth 1         \
            -type f             \
            -readable           \
            -not -name '*~'     \
            -not -name '.git*'  \
            -not -name 'LIC*'   \
            -not -name 'READ*'  \
            -printf '_ %f\r\n'  |
    sort
    )"
aant=$(eval "$opdr1" | wc --lines)

opdr2="$opdr1                           |
        pr  --indent=8                  \
            --form-feed                 \
            --date-format='%a %d %b %Y' \
            --header='$PROGNAME - Overzicht van alle kz-scripts ($aant)'"
eval "$opdr2"

while true; do
    read -rp 'Resultaat afdrukken? [j/N]: ' </dev/tty
    case $REPLY in
        j* | J*)
            eval "$opdr2" | lpr
            echo 'Overzicht is verzonden naar de printer.'
            break
            ;;
        n* | N* | '')
            echo 'Overzicht is alleen naar het scherm verzonden.'
            break
            ;;
        *)
            echo -e "${UP_1_LINE}${ERASE_LINE}"
            continue
            ;;
    esac
done

# Einde script
