#!/bin/bash
set -o errexit
set -o nounset

# lsrv0097: synchronise /home/zimmerce from lsrv0100 to lsrv0097

source=/home/zimmerce
target=zimmerce@lsrv0097:/home/zimmerce

rsync   --archive   \
        --verbose   \
        --delete    \
        "$source"/  \
        "$target"/
