#!/bin/bash
set -o errexit
set -o nounset

# lsrv0100: synchronise /home/zimmerce from lsrv0097 to lsrv0100

source=zimmerce@lsrv0097:/home/zimmerce
target=zimmerce@lsrv0100:/home/zimmerce

rsync   --archive   \
        --verbose   \
        --delete    \
        "$source"/  \
        "$target"/
