#!/usr/bin/env bash
###############################################################################
# SPDX-FileComment: Generate .mo and copy it to the correct location
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
set -o errexit
set -o nounset

lc_messages=/home/"$USER"/kz-scripts/usr/share/locale/nl/LC_MESSAGES
msgfmt --output-file="$lc_messages"/kz.mo  "$lc_messages"/kz.po
sudo cp "$lc_messages"/kz.mo /usr/share/locale/nl/LC_MESSAGES/kz.mo
