#!/usr/bin/env bash
# shellcheck source=common.sh
###############################################################################
# SPDX-FileComment: Generate a MO file and copy it to the appropriate location
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################

###############################################################################
# Imports
###############################################################################

source common.sh


###############################################################################
# Constants
###############################################################################

readonly LC_MESSAGES_DIR=$HOME/kz-scripts/usr/share/locale/nl/LC_MESSAGES


###############################################################################
# Globals
###############################################################################


###############################################################################
# Main
###############################################################################

init_script

msgfmt --output-file="$LC_MESSAGES_DIR/kz.mo" "$LC_MESSAGES_DIR/kz.po"
sudo cp "$LC_MESSAGES_DIR/kz.mo" /usr/share/locale/nl/LC_MESSAGES/kz.mo

printf '%s\n' "$(gettext 'Complete!')"
exit 0
