#!/usr/bin/env bash
# shellcheck source=common.sh
###############################################################################
# SPDX-FileComment: Update .pot and merge with existing .po
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################

###############################################################################
# Imports
###############################################################################

source common.sh


###############################################################################
# Constants
###############################################################################

readonly SCRIPTS_REPO=$HOME/kz-scripts
readonly GETTEXT_DIRS="\
/home/$USER/kz-scripts/usr/bin \
/home/$USER/kz-scripts/usr/share/applications
/home/$USER/kz-scripts/usr/share/polkit-1/actions
"

###############################################################################
# Globals
###############################################################################


###############################################################################
# Main
###############################################################################

init_script

for dir in $GETTEXT_DIRS; do

    cd "$dir" || exit 1

    for file in *; do
        dir_file="$dir/$file"
        if [[ -d $file ]]; then
            echo "$dir_file: is een map"
            continue
        elif [[ $file =~ .*.gpg$ ]]; then
            echo "$dir_file: is GPG versleuteld"
            continue
        elif [[ $file =~ .*.policy$ ]]; then
            echo "$dir_file: Polkit bestanden nog niet ondersteund"
            continue
        elif [[ $file =~ .*.pot$ ]]; then
            echo "$dir_file: is een GNU gettext message catalogue"
            continue
        elif ! [[ -f $file ]]; then
            echo "$dir_file: is geen bestand"
            continue
        fi

        if grep --quiet '^# shellcheck ' "$file"; then
            language='Shell'
        elif grep --quiet '^import ' "$file"; then
            language='Python'
        elif grep --quiet 'Desktop Entry' "$file"; then
            language='Desktop'
        elif grep --quiet 'policyconfig' "$file"; then
            language='Policy'
        else
            echo "$dir_file: kan de taal (Shell, Python, Desktop, of \
Policy) niet bepalen"
            continue
        fi

        printf '%s' "$dir_file: "

        xgettext    --language="$language"                      \
                    --join-existing                             \
                    --package-name='kz'                         \
                    --package-version='4.2.1'                   \
                    --msgid-bugs-address='info@karelzimmer.nl'  \
                    --output="$SCRIPTS_REPO/usr/bin/kz.pot"     \
                    "$file"

        msgmerge    --update                                                \
                    --backup=none                                           \
                    --previous                                              \
                    "$SCRIPTS_REPO/usr/share/locale/nl/LC_MESSAGES/kz.po"   \
                    "$SCRIPTS_REPO/usr/bin/kz.pot"
    done
done

printf '%s\n' "$(gettext 'Complete!')"
exit 0
