#!/usr/bin/bash
###############################################################################
# SPDX-FileComment: Update .pot and merge with existing .po
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
set -o errexit
set -o nounset

language='Pipo'
proj_dir=/home/$USER/kz-scripts

function policy_file {
	printf '\n%s\n' "### $script ###"
	printf '%s\n' 'Utility xgettext ondersteunt nog geen Policy bestanden.

Voer de volgende 3 wijzigingen handmatig uit.

1. Wijzig in .policy bestand:
        <description>DESC-EN</description>
        <description xml:lang="nl">DESC-NL</description>
        <message>MSG-EN</message>
        <message xml:lang="nl">MSG-NL</message>
   naar:
        <description gettext-domain="kz">DESC-EN</description>
        <message gettext-domain="kz">MSG-EN</message>

2. Voeg toe aan .pot bestand als nodig:
msgid "DESC-EN"
msgstr ""

msgid "MSG-EN"
msgstr ""

3. Voeg toe aan .po bestand als nodig:
msgid "DESC-EN"
msgstr "DESC-NL"

msgid "MSG-EN"
msgstr "MSG-NL"'
}

if [[ -z "$*" ]]; then
    echo 'Gebruik: pogen SCRIPT'
    exit 1
fi

cd "$PWD" || exit 1

for script in "$@"; do
    if ! [[ -f $script ]]; then
        echo "$script bestaat niet."
        continue
    fi

    if grep --quiet '^# shellcheck ' "$script"; then
        language='Shell'
    elif grep --quiet '^import ' "$script"; then
        language='Python'
    elif grep --quiet 'Desktop Entry' "$script"; then
        language='Desktop'
    elif grep --quiet 'policyconfig' "$script"; then
        language='Policy'
    else
        echo 'Kan de taal (Shell, Python, Desktop, of Policy) niet bepalen.'
        continue
    fi

    if [[ $language = 'Policy' ]]; then
        policy_file
        continue
    fi

    printf '%s' "$script"

    xgettext    --language=$language    \
                --join-existing         \
                --no-location           \
                --output="$proj_dir"/usr/bin/kz.pot "$script"

    msgmerge    --update                                            \
                --backup=none                                       \
                --previous                                          \
                --no-location                                       \
                "$proj_dir"/usr/share/locale/nl/LC_MESSAGES/kz.po   \
                "$proj_dir"/usr/bin/kz.pot
    shift
done
