#!/bin/bash
set -o errexit
set -o nounset

# pogenpy: generate .pot and merge with existing .po for Python scripts

cd ~/kz-scripts/usr/bin
echo "Generate kz.pot"
xgettext --language=Python --join-existing --no-location --output=kz.pot "$1"
echo "Generate kz.po"
msgmerge --update --backup=none --previous --no-location ../share/locale/nl/LC_MESSAGES/kz.po kz.pot
