#!/usr/bin/bash
###############################################################################
# SPDX-FileComment: Update .pot and merge with existing .po
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
set -o errexit
set -o nounset

language='Pipo'
proj_dir=/home/$USER/kz-scripts

if [[ -z "$*" ]]; then
    echo 'Gebruik: pogen SCRIPT...'
    exit 1
fi

function policy_file {
	printf '%s\n' "### $script ###"
	printf '%s\n' 'Utility xgettext ondersteunt (nog) geen Policy bestanden.

Voer de volgende stappen handmatig uit.

1. Wijzig .policy bestand:
        <description gettext-domain="kz">DESC-EN</description>
        <message gettext-domain="kz">MSG-EN</message>

2. Voeg toe aan .pot bestand als nodig:
msgid "DESC-EN"
msgstr ""

msgid "MSG-EN"
msgstr ""

3. Voeg toe aan .po bestand als nodig:
msgid "DESC-EN"
msgstr "DESC-NL"

msgid "MSG-EN"
msgstr "MSG-NL"

4. Voer mogen uit.

5. Test de vertaling.'
}

function desktop_file {
	printf '%s\n' "### $script ###"
	printf '%s\n' 'Utility xgettext ondersteunt (nog) geen Desktop bestanden.

Voer de volgende stappen handmatig uit.

1. Wijzig .desktop bestand:
Comment=DESC-EN
Categories=...;X-GNOME-Utilities;
X-GNOME-Gettext-Domain=kz
X-Ubuntu-Gettext-Domain=kz

2. Voeg toe aan .pot bestand als nodig:
msgid "DESC-EN"
msgstr ""

3. Voeg toe aan .po bestand als nodig:
msgid "DESC-EN"
msgstr "DESC-NL"

4. Voer mogen uit.

5. Test de vertaling.'
}

cd "$PWD" || exit 1

for script in "$@"; do
    if ! [[ -f $script ]]; then
        echo "$script bestaat niet."
        continue
    fi

    if grep --quiet '^# shellcheck ' "$script"; then
        language='Shell'
    elif grep --quiet '^import ' "$script"; then
        language='Python'
    elif grep --quiet 'Desktop Entry' "$script"; then
        language='Desktop'
    elif grep --quiet 'policyconfig' "$script"; then
        language='Policy'
    else
        echo "$script: kan de taal (Shell, Python, Desktop, of Policy) niet be\
palen"
        continue
    fi

    if [[ $language = 'Policy' ]]; then
        policy_file
        continue
    elif  [[ $language = 'Desktop' ]]; then
        desktop_file
        continue
    fi

    printf '%s' "$script"

    xgettext    --language=$language    \
                --join-existing         \
                --no-location           \
                --output="$proj_dir"/usr/bin/kz.pot "$script"

    msgmerge    --update                                            \
                --backup=none                                       \
                --previous                                          \
                --no-location                                       \
                "$proj_dir"/usr/share/locale/nl/LC_MESSAGES/kz.po   \
                "$proj_dir"/usr/bin/kz.pot
done
