#!/usr/bin/bash
set -o errexit
set -o nounset

# rchecklink: reverse checklink

# Perl script checklink (W3C® Link Checker) checks whether links are valid,
# i.e. whether each link can be followed/whether a file is present.
# This Bash script does the opposite: are all files used?

dir1=/home/$USER/kz-uploads/app/assets
dir2=/home/$USER/kz-uploads/dist/assets
html=/home/$USER/kz-uploads/dist/html

declare -i check=0

while read -r file; do
    if ! grep --recursive --quiet "$(basename "$file")" "$html"; then
        case $file in
            *-pc0*|*-pc-*|*kz-vm-hugowin732.desktop*)
                continue
                ;;
            *icons/LF*)
                continue
                ;;
            *assets/citrix*)
                continue
                ;;
            *)
                :
                ;;
        esac
        ((++check))
        printf '%s\n%s\n' 'File that probably can be deleted:' "$file"
    fi
done < <(find "$dir1" "$dir2" -type f -print | sort)
if [[ $check -gt 0 ]]; then
    exit 1
fi

# Difference between app/ and dist/.
diff    --recursive                     \
        "/home/$USER/kz-uploads/app/"   \
        "/home/$USER/kz-uploads/dist/"  \
        --exclude='kz'                  \
        --exclude='kz-docs'             \
        --exclude='kz-scripts'          || true

# Perl script checklink (W3C® Link Checker) checks whether links are valid.
# Check the validity of links in linux.html:
# sudo apt-get install w3c-linkchecker
# checklink --summary https://$USERzimmer.nl/html/nl/linux.html 2> /dev/null
# checklink --summary https://$USERzimmer.nl/html/en/linux.html 2> /dev/null
