#!/usr/bin/bash
###############################################################################
# SPDX-FileComment: Reverse checklink
#
# Perl script checklink (W3C® Link Checker) checks whether links are valid,
# i.e. whether each link can be followed/whether a file is present.
# This Bash script does the opposite: are all files used?
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
set -o errexit
set -o nounset

readonly NORMAL='\033[0m'
readonly GREEN='\033[1;32m'
readonly PROGRAM_NAME='rchecklink'
readonly DIR1=/$HOME/kz-upload/src/assets
readonly DIR2=/$HOME/kz-upload/dist/assets
readonly HTML=/$HOME/kz-upload/dist/html

declare -i check=0

# Check files which are not used on the html pages.
while read -r file; do
    if ! grep --recursive --quiet "$(basename "$file")" "$HTML"; then
        case $file in
            *icons/LF*)
                continue
                ;;
            *)
                :
                ;;
        esac
        ((++check))
        if [[ check -eq 1 ]]; then
            printf '%s\n' 'Files that probably can be deleted:'
        fi
        printf 'rm %s\n' "$file"
    fi
done < <(find "$DIR1" "$DIR2" -type f -print | sort)
if [[ $check -gt 0 ]]; then
    exit 1
fi

# Difference between src/ and dist/.
if ! diff   --recursive                     \
            "/$HOME/kz-upload/src/"   \
            "/$HOME/kz-upload/dist/"  \
            --exclude='kz'                  \
            --exclude='kz-docs'; then
    exit 1
fi
printf "$GREEN%b$NORMAL\n" "$PROGRAM_NAME $(gettext --domain=kz 'finished')"

# Perl script checklink (W3C® Link Checker) checks whether links are valid.
# Check the validity of links in linux.html:
# sudo apt-get install w3c-linkchecker
# checklink --summary https://karelzimmer.nl/html/nl/start.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/nl/linux.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/nl/waarom-linux.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/nl/contact.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/nl/zoeken.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/en/linux.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/en/home.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/en/linux.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/en/why-linux.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/en/contact.html 2> /dev/null
# checklink --summary https://karelzimmer.nl/html/en/search.html 2> /dev/null
