#!/usr/bin/env bash
# #############################################################################
# SPDX-FileComment: Renamen van bestanden.
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
# #############################################################################

# init
# Renamen van BACKUP_<host>_<user> naar backup_<host>_<user>
# Usage:
# 1. cd <directory containing the BACKUP_* files>
# 2. sudo ~/bin/rename

# verwerk
for file in BACKUP_*; do
    user_host=$(echo "$file" | cut --delimiter='_' --fields=2-3)
    host=$(echo "$user_host" | cut --delimiter='_' --fields=1)
    user=$(echo "$user_host" | cut --delimiter='_' --fields=2)
    echo "mv $file backup_${host}_${user}"
    # mv --verbose "$file" "backup_${host}_${user}"
done

# afsl_script
exit 0
