#!/bin/bash

# Persoonlijke map herstellen.

target=$(ls --directory /media/"$USER"/* 2> /dev/null)
target=$HOME
if [[ -z $source ]]; then
    echo 'Sluit USB-harddisk aan.'
    exit 1
fi
exclude=$(mktemp -t 'backup-XXXXXXXXXX')
distro=$(lsb_release --id --short | tr '[:upper:]' '[:lower:]')

cat << EOF > "$exclude"
$(find /etc/skel -type f -exec basename '{}' \;)
EOF

rsync   --archive                                   \
        --verbose                                   \
        --human-readable                            \
        --exclude-from="$exclude"                   \
        "$source/backup-$HOSTNAME-$distro-$USER"/   \
        "$target"

rm "$exclude"
