#!/bin/bash

# Back-up van Persoonlijke map terugzetten.

source=$(ls --directory /media/"$USER"/* 2> /dev/null)
target=$HOME
if [[ -z $source || $(echo "$source" | wc --lines) -gt 1 ]]; then
    echo 'Sluit één USB-harddisk aan.'
    exit 1
fi
exclude=$(mktemp -t 'restore-XXXXXXXXXX')

# With a new version of the OS, these could have been changed, hence excluded.
cat << EOF > "$exclude"
$(find /etc/skel -type f -exec basename '{}' \;)
EOF

rsync   --archive                           \
        --progress                          \
        --human-readable                    \
        --exclude-from="$exclude"           \
        "$source/backup-$HOSTNAME-$USER"/   \
        "$target"

rm "$exclude"
