#!/bin/bash

# Back-up van Persoonlijke map terugzetten.

source=$(ls --directory /media/"$USER"/* 2> /dev/null)
target=$HOME
if [[ -z $source || $(echo "$source" | wc --lines) -gt 1 ]]; then
    echo 'Sluit één USB-harddisk aan.'
    exit 1
fi

rsync   --archive                           \
        --verbose                           \
        --human-readable                    \
        "$source/backup-$HOSTNAME-$USER"/   \
        "$target"
