#!/usr/bin/bash
###############################################################################
# Split checksum files.
#
# This script creates an .iso.sha256 with the checksum for an .iso.
#
# Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
# <https://creativecommons.org/publicdomain/zero/1.0>, 2021-2023.
###############################################################################

###############################################################################
# Constants
###############################################################################

readonly SEARCHDIR=$HOME/Downloads

###############################################################################
# Variables
###############################################################################

declare iso=''
declare -i grep_rc=0

###############################################################################
# Script
###############################################################################

cd "$SEARCHDIR" || exit 1

for iso in *.iso; do
    grep_rc=0
    # shellcheck disable=SC2062
    grep    --word-regexp           \
            --regexp=" $iso"        \
            --regexp=' *'"$iso"     \
            --exclude=*.iso         \
            --exclude="$iso".sha256    \
            --exclude-dir=*         \
            --no-filename           \
            --max-count=1           \
            -- *                    > "$iso".sha256 || grep_rc=$?
    if [[ $grep_rc -ne 0 ]]; then
        rm "$iso".sha256
        printf '%s\n' "No checksum found for $iso." >&2
    else
        printf '%s\n' "Checksum file $iso.sha256 created."
    fi
done
printf  '\n%s\n%s\n'                                \
        'To check the image files (.iso) execute:'  \
        "cd $SEARCHDIR; sha256sum --check *.iso.sha256; cd -"

printf '\n%s\n' 'Files that probably can be deleted:'
ls -1 -- "$SEARCHDIR"/*{sum,SUM}* 2>/dev/null

printf '\n%s\n' 'Finished.'
