#!/bin/bash

# Systeem bijwerken.

sudo apt-get update
sudo apt-get upgrade --yes
sudo apt-get autoremove --yes
sudo apt-get autoclean --yes
sudo snap refresh
if [[ -f /var/run/reboot-required ]]; then echo REBOOT; fi
