#!/usr/bin/bash

# ventoy: copy all files in Downloads directory to Ventoy USB stick

cd ~/Downloads || exit 1
for file in *; do
    echo "$(date) Copying $file... "
    cp "$file" /media/karel/Ventoy/
    echo "$(date) Copied $file."
done